name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
      - name: Run tests
        run: swift test -v
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
